"""sync

Revision ID: 15d12e9d5028
Revises: 37e2bf3d3751
Create Date: 2026-01-20 17:25:54.806110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d12e9d5028'
down_revision: Union[str, Sequence[str], None] = '37e2bf3d3751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_course_lesson'), 'lessons', type_='unique')
    op.create_index(op.f('ix_lessons_order'), 'lessons', ['order'], unique=False)
    op.create_unique_constraint('uq_module_lesson', 'lessons', ['course_id', 'order'])
    op.drop_column('lessons', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_module_lesson', 'lessons', type_='unique')
    op.drop_index(op.f('ix_lessons_order'), table_name='lessons')
    op.create_unique_constraint(op.f('uq_course_lesson'), 'lessons', ['course_id', 'number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
