"""sync

Revision ID: 16681b05e717
Revises: 20131969507a
Create Date: 2026-01-08 11:00:29.544288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16681b05e717'
down_revision: Union[str, Sequence[str], None] = '20131969507a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_categories',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'category_id')
    )
    op.create_table('modules',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'order', name='uq_module_order'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_modules_course_id'), 'modules', ['course_id'], unique=False)
    op.create_table('module_results',
    sa.Column('module_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('project_score', sa.Integer(), nullable=True),
    sa.Column('exam_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('module_id', 'student_id', name='uq_module_student')
    )
    op.create_table('lesson_assessments',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('lesson_assignments',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_index(op.f('ix_baskets_is_deleted'), table_name='baskets')
    op.drop_index(op.f('ix_baskets_user_id'), table_name='baskets')
    # op.drop_table('baskets')
    op.execute('DROP TABLE baskets CASCADE')
    op.drop_index(op.f('ix_tags_display_order'), table_name='tags')
    op.drop_index(op.f('ix_tags_featured_order'), table_name='tags')
    op.drop_index(op.f('ix_tags_is_active'), table_name='tags')
    op.drop_index(op.f('ix_tags_is_featured'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_name_active'), table_name='tags')
    op.drop_index(op.f('ix_tags_parent_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_search_vector'), table_name='tags')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_index(op.f('ix_tags_slug_active'), table_name='tags')
    op.drop_index(op.f('ix_tags_usage_count'), table_name='tags')
    # op.drop_table('tags')
    op.execute('DROP TABLE tags CASCADE')
    op.drop_index(op.f('ix_favorites_is_default'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_is_deleted'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_user_default'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    # op.drop_table('favorites')
    op.execute('DROP TABLE favorites CASCADE')
    op.drop_table('user_avatars')
    op.drop_index(op.f('ix_favorite_items_favorite_id'), table_name='favorite_items')
    op.drop_index(op.f('ix_favorite_items_favorite_product'), table_name='favorite_items')
    op.drop_index(op.f('ix_favorite_items_is_deleted'), table_name='favorite_items')
    op.drop_index(op.f('ix_favorite_items_product_id'), table_name='favorite_items')
    op.drop_index(op.f('ix_favorite_items_variant_id'), table_name='favorite_items')
    # op.drop_table('favorite_items')
    op.execute('DROP TABLE favorite_items CASCADE')
    op.drop_index(op.f('ix_product_created_at'), table_name='products')
    op.drop_index(op.f('ix_product_name'), table_name='products')
    op.drop_index(op.f('ix_product_price'), table_name='products')
    op.drop_index(op.f('ix_product_slug'), table_name='products')
    op.drop_index(op.f('ix_product_status'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    # op.drop_table('products')
    op.execute('DROP TABLE products CASCADE')
    op.drop_index(op.f('ix_product_variants_barcode'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_is_active'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_active'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_stock'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_stock_quantity'), table_name='product_variants')
    # op.drop_table('product_variants')
    op.execute('DROP TABLE product_variants CASCADE')
    op.drop_index(op.f('ix_attributes_key'), table_name='product_attributes')
    op.drop_index(op.f('ix_product_attributes_product_id'), table_name='product_attributes')
    op.drop_table('product_attributes')
    op.drop_index(op.f('ix_orders_address_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_tracking_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    # op.drop_table('orders')
    op.execute('DROP TABLE orders CASCADE')
    op.drop_table('users_products')
    op.drop_table('product_tags')
    op.drop_index(op.f('ix_scores_enrollment_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_lesson_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_recorder_id'), table_name='scores')
    # op.drop_table('scores')
    op.execute('DROP TABLE scores CASCADE')
    op.drop_index(op.f('ix_product_images_is_cover'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_basket_items_basket_id'), table_name='basket_items')
    op.drop_index(op.f('ix_basket_items_product_id'), table_name='basket_items')
    op.drop_table('basket_items')
    op.drop_table('products_categories')
    op.create_unique_constraint('uq_lesson_student_attendance', 'attendance', ['lesson_id', 'student_id'])
    op.add_column('certificates', sa.Column('course_id', sa.Uuid(), nullable=False))
    op.add_column('certificates', sa.Column('issued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('certificates_verification_token_key'), 'certificates', type_='unique')
    op.drop_index(op.f('ix_certificates_certificate_number'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_enrollment_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_issued_by'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_student_id'), table_name='certificates')
    op.create_unique_constraint('uq_certificate', 'certificates', ['student_id', 'course_id'])
    op.drop_constraint(op.f('certificates_enrollment_id_fkey'), 'certificates', type_='foreignkey')
    op.drop_constraint(op.f('certificates_issued_by_fkey'), 'certificates', type_='foreignkey')
    op.create_foreign_key(None, 'certificates', 'courses', ['course_id'], ['id'])
    op.drop_column('certificates', 'is_revoked')
    op.drop_column('certificates', 'qr_code_url')
    op.drop_column('certificates', 'expiry_date')
    op.drop_column('certificates', 'title')
    op.drop_column('certificates', 'final_score')
    op.drop_column('certificates', 'enrollment_id')
    op.drop_column('certificates', 'issue_date')
    op.drop_column('certificates', 'revoked_reason')
    op.drop_column('certificates', 'completion_rate')
    op.drop_column('certificates', 'certificate_number')
    op.drop_column('certificates', 'issued_by')
    op.drop_column('certificates', 'verification_token')
    op.drop_column('certificates', 'overall_grade')
    op.add_column('contact_infos', sa.Column('user_id', sa.Uuid(), nullable=True))
    # op.drop_constraint(op.f('contact_infos_product_id_fkey'), 'contact_infos', type_='foreignkey')
    op.create_foreign_key(None, 'contact_infos', 'users', ['user_id'], ['id'])
    op.drop_column('contact_infos', 'product_id')
    op.drop_column('courses', 'short_description')
    op.add_column('enrollments', sa.Column('enrolled_by', sa.Uuid(), nullable=True))
    op.add_column('enrollments', sa.Column('enrolled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.create_unique_constraint('uq_student_course', 'enrollments', ['student_id', 'course_id'])
    op.create_foreign_key(None, 'enrollments', 'users', ['enrolled_by'], ['id'])
    op.drop_column('enrollments', 'session')
    op.drop_column('enrollments', 'completed_date')
    op.drop_column('enrollments', 'enrolled_date')
    op.drop_column('enrollments', 'term')
    op.add_column('lessons', sa.Column('module_id', sa.Uuid(), nullable=False))
    op.add_column('lessons', sa.Column('lesson_date', sa.Date(), nullable=False))
    op.alter_column('lessons', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.drop_constraint(op.f('uq_course_lesson'), 'lessons', type_='unique')
    op.create_unique_constraint('uq_module_lesson_number', 'lessons', ['module_id', 'lesson_number'])
    op.drop_constraint(op.f('lessons_course_id_fkey'), 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_column('lessons', 'course_id')
    op.drop_column('lessons', 'order')
    op.drop_column('lessons', 'has_assignment')
    op.drop_column('lessons', 'has_assessment')
    op.add_column('locations', sa.Column('user_id', sa.Uuid(), nullable=True))
    # op.drop_constraint(op.f('locations_product_id_fkey'), 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'users', ['user_id'], ['id'])
    op.drop_column('locations', 'product_id')
    op.add_column('payments', sa.Column('course_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_course_id'), 'payments', ['course_id'], unique=False)
    # op.drop_constraint(op.f('payments_order_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.drop_column('payments', 'order_id')
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_score_id'), table_name='reviews')
    # op.drop_constraint(op.f('reviews_product_id_fkey'), 'reviews', type_='foreignkey')
    # op.drop_constraint(op.f('reviews_score_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'product_id')
    op.drop_column('reviews', 'score_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('score_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('reviews_score_id_fkey'), 'reviews', 'scores', ['score_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reviews_product_id_fkey'), 'reviews', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_reviews_score_id'), 'reviews', ['score_id'], unique=False)
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.add_column('payments', sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_order_id_fkey'), 'payments', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_payments_course_id'), table_name='payments')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.drop_column('payments', 'course_id')
    op.add_column('locations', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key(op.f('locations_product_id_fkey'), 'locations', 'products', ['product_id'], ['id'])
    op.drop_column('locations', 'user_id')
    op.add_column('lessons', sa.Column('has_assessment', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('has_assignment', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key(op.f('lessons_course_id_fkey'), 'lessons', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_module_lesson_number', 'lessons', type_='unique')
    op.create_unique_constraint(op.f('uq_course_lesson'), 'lessons', ['course_id', 'lesson_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.alter_column('lessons', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('lessons', 'lesson_date')
    op.drop_column('lessons', 'module_id')
    op.add_column('enrollments', sa.Column('term', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('enrollments', sa.Column('enrolled_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('enrollments', sa.Column('completed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('enrollments', sa.Column('session', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint('uq_student_course', 'enrollments', type_='unique')
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.drop_column('enrollments', 'enrolled_at')
    op.drop_column('enrollments', 'enrolled_by')
    op.add_column('courses', sa.Column('short_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('contact_infos', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contact_infos', type_='foreignkey')
    op.create_foreign_key(op.f('contact_infos_product_id_fkey'), 'contact_infos', 'products', ['product_id'], ['id'])
    op.drop_column('contact_infos', 'user_id')
    op.add_column('certificates', sa.Column('overall_grade', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('verification_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('issued_by', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('certificates', sa.Column('certificate_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('certificates', sa.Column('completion_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('revoked_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('issue_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('certificates', sa.Column('enrollment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('certificates', sa.Column('final_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('certificates', sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('qr_code_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.create_foreign_key(op.f('certificates_issued_by_fkey'), 'certificates', 'users', ['issued_by'], ['id'])
    op.create_foreign_key(op.f('certificates_enrollment_id_fkey'), 'certificates', 'enrollments', ['enrollment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_certificate', 'certificates', type_='unique')
    op.create_index(op.f('ix_certificates_student_id'), 'certificates', ['student_id'], unique=False)
    op.create_index(op.f('ix_certificates_issued_by'), 'certificates', ['issued_by'], unique=False)
    op.create_index(op.f('ix_certificates_enrollment_id'), 'certificates', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_certificates_certificate_number'), 'certificates', ['certificate_number'], unique=True)
    op.create_unique_constraint(op.f('certificates_verification_token_key'), 'certificates', ['verification_token'], postgresql_nulls_not_distinct=False)
    op.drop_column('certificates', 'issued_at')
    op.drop_column('certificates', 'course_id')
    op.drop_constraint('uq_lesson_student_attendance', 'attendance', type_='unique')
    op.create_table('products_categories',
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('products_categories_category_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('products_categories_product_id_fkey')),
    sa.PrimaryKeyConstraint('category_id', 'product_id', name=op.f('products_categories_pkey'))
    )
    op.create_table('basket_items',
    sa.Column('basket_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], name=op.f('basket_items_basket_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('basket_items_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('basket_items_pkey')),
    sa.UniqueConstraint('id', name=op.f('basket_items_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_basket_items_product_id'), 'basket_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_basket_items_basket_id'), 'basket_items', ['basket_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=140), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('variant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_items_order_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('order_items_product_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('order_items_variant_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('order_items_pkey')),
    sa.UniqueConstraint('id', name=op.f('order_items_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_cover', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['file_uploads.id'], name=op.f('product_images_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_images_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_images_pkey'))
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_images_is_cover'), 'product_images', ['is_cover'], unique=False)
    op.create_table('scores',
    sa.Column('enrollment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recorder_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('ASSIGNMENT', 'ASSESSMENT', 'QUIZ', 'EXAM', 'PROJECT', 'HOMEWORK', 'CLASSWORK', 'LAB', 'PRESENTATION', 'OTHER', name='assessmenttype'), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('grade', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_final', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('recorded_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('score >= 0::double precision AND score <= 100::double precision', name=op.f('check_assessment')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('scores_assessment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('scores_enrollment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('scores_lesson_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorder_id'], ['users.id'], name=op.f('scores_recorder_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('scores_pkey')),
    sa.UniqueConstraint('enrollment_id', 'lesson_id', name=op.f('uq_enrollment_lesson'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('id', name=op.f('scores_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_scores_recorder_id'), 'scores', ['recorder_id'], unique=False)
    op.create_index(op.f('ix_scores_lesson_id'), 'scores', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_scores_enrollment_id'), 'scores', ['enrollment_id'], unique=False)
    op.create_table('product_tags',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('relevance', sa.INTEGER(), autoincrement=False, nullable=False, comment='Relevance score (1-10), higher means more relevant'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_tags_product_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('product_tags_tag_id_fkey'), ondelete='CASCADE')
    )
    op.create_table('users_products',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('users_products_product_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('users_products_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'product_id', name=op.f('users_products_pkey'))
    )
    op.create_table('orders',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tracking_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'canceled', 'refunded', name='orderstatus'), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('tax_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('shipping_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('delivery_time_slot', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('delivery_option', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('picked_up_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rider_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name=op.f('orders_address_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('orders_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey')),
    sa.UniqueConstraint('id', name=op.f('orders_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_tracking_number'), 'orders', ['tracking_number'], unique=True)
    op.create_index(op.f('ix_orders_address_id'), 'orders', ['address_id'], unique=False)
    op.create_table('product_attributes',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_attributes_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_attributes_pkey')),
    sa.UniqueConstraint('id', name=op.f('product_attributes_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_product_attributes_product_id'), 'product_attributes', ['product_id'], unique=False)
    op.create_index(op.f('ix_attributes_key'), 'product_attributes', ['key'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Stock Keeping Unit - unique identifier'),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment="Variant display name, e.g., 'Large - Blue'"),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='JSON object containing variant attributes'),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False, comment='Variant-specific price (can differ from base product)'),
    sa.Column('compare_at_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Original price for showing discounts'),
    sa.Column('cost_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Cost price for profit calculations'),
    sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('low_stock_threshold', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Weight in kg'),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='JSON: {length, width, height} in cm'),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Primary variant image'),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Array of additional image URLs'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether this is the default variant for the product'),
    sa.Column('is_tracked', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether inventory is tracked for this variant'),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False, comment='Display position among variants'),
    sa.Column('barcode', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='UPC/EAN/ISBN barcode'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('price >= 0::numeric', name='ck_product_variant_price_positive'),
    sa.CheckConstraint('stock_quantity >= 0', name='ck_product_variant_stock_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_variants_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='product_variants_pkey'),
    sa.UniqueConstraint('id', name='product_variants_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('product_id', 'sku', name='uq_product_variant_sku', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_product_variants_stock_quantity'), 'product_variants', ['stock_quantity'], unique=False)
    op.create_index(op.f('ix_product_variants_stock'), 'product_variants', ['stock_quantity'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_active'), 'product_variants', ['product_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_product_variants_is_active'), 'product_variants', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_variants_barcode'), 'product_variants', ['barcode'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'published', 'archived', name='product_status'), autoincrement=False, nullable=False),
    sa.Column('listing_type', postgresql.ENUM('product', 'service', 'rental', 'property', 'vehicle', name='listing_types'), autoincrement=False, nullable=False),
    sa.Column('average_rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    sa.UniqueConstraint('id', name='products_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_product_status'), 'products', ['status'], unique=False)
    op.create_index(op.f('ix_product_slug'), 'products', ['slug'], unique=False)
    op.create_index(op.f('ix_product_price'), 'products', ['price'], unique=False)
    op.create_index(op.f('ix_product_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_product_created_at'), 'products', ['created_at'], unique=False)
    op.create_table('favorite_items',
    sa.Column('favorite_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('variant_id', sa.UUID(), autoincrement=False, nullable=True, comment='Optional: specific product variant'),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True, comment='User notes about this favorite item'),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False, comment='User-defined priority/order within the list'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('product_snapshot', sa.TEXT(), autoincrement=False, nullable=True, comment='Snapshot of product details when favorited'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorites.id'], name=op.f('favorite_items_favorite_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('favorite_items_product_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('favorite_items_variant_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('favorite_items_pkey')),
    sa.UniqueConstraint('favorite_id', 'product_id', 'variant_id', name=op.f('uq_favorite_product_variant'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('id', name=op.f('favorite_items_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_favorite_items_variant_id'), 'favorite_items', ['variant_id'], unique=False)
    op.create_index(op.f('ix_favorite_items_product_id'), 'favorite_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_favorite_items_is_deleted'), 'favorite_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_favorite_items_favorite_product'), 'favorite_items', ['favorite_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_favorite_items_favorite_id'), 'favorite_items', ['favorite_id'], unique=False)
    op.create_table('user_avatars',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['file_uploads.id'], name=op.f('user_avatars_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_avatars_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_avatars_pkey'))
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('privacy', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='private, public, or shared'),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('favorites_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('favorites_pkey')),
    sa.UniqueConstraint('id', name=op.f('favorites_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', 'name', name=op.f('uq_user_favorite_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_default'), 'favorites', ['user_id', 'is_default'], unique=False)
    op.create_index(op.f('ix_favorites_is_deleted'), 'favorites', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_favorites_is_default'), 'favorites', ['is_default'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Display name of the tag'),
    sa.Column('slug', sa.VARCHAR(length=150), autoincrement=False, nullable=False, comment='URL-friendly version of the name'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Detailed description for SEO and display'),
    sa.Column('meta_title', sa.VARCHAR(length=150), autoincrement=False, nullable=True, comment='Custom meta title for SEO'),
    sa.Column('meta_description', sa.VARCHAR(length=300), autoincrement=False, nullable=True, comment='Custom meta description for SEO'),
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Icon class or image URL'),
    sa.Column('color', sa.VARCHAR(length=7), autoincrement=False, nullable=True, comment='Hex color code for UI (#RRGGBB)'),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False, comment='Order in which tag appears in listings'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Featured tags appear in special sections'),
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='System tags cannot be deleted by users'),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='Number of products using this tag'),
    sa.Column('click_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='Number of clicks on this tag'),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Last time a product was tagged with this'),
    sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True, comment='Full-text search vector for name and description'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tags.id'], name=op.f('tags_parent_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tags_pkey')),
    sa.UniqueConstraint('id', name=op.f('tags_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tags_usage_count'), 'tags', ['usage_count'], unique=False)
    op.create_index(op.f('ix_tags_slug_active'), 'tags', ['slug', 'is_active'], unique=False)
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_index(op.f('ix_tags_search_vector'), 'tags', ['search_vector'], unique=False)
    op.create_index(op.f('ix_tags_parent_id'), 'tags', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tags_name_active'), 'tags', ['name', 'is_active'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_index(op.f('ix_tags_is_featured'), 'tags', ['is_featured'], unique=False)
    op.create_index(op.f('ix_tags_is_active'), 'tags', ['is_active'], unique=False)
    op.create_index(op.f('ix_tags_featured_order'), 'tags', ['is_featured', 'display_order'], unique=False)
    op.create_index(op.f('ix_tags_display_order'), 'tags', ['display_order'], unique=False)
    op.create_table('baskets',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('baskets_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('baskets_pkey')),
    sa.UniqueConstraint('id', name=op.f('baskets_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_baskets_user_id'), 'baskets', ['user_id'], unique=False)
    op.create_index(op.f('ix_baskets_is_deleted'), 'baskets', ['is_deleted'], unique=False)
    op.drop_table('lesson_assignments')
    op.drop_table('lesson_assessments')
    op.drop_table('module_results')
    op.drop_index(op.f('ix_modules_course_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_table('course_categories')
    # ### end Alembic commands ###
