"""sync

Revision ID: 16fa66b1e79b
Revises: aaecb890565d
Create Date: 2026-01-23 12:51:12.645441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16fa66b1e79b'
down_revision: Union[str, Sequence[str], None] = 'aaecb890565d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_columns',
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('module_id', sa.Uuid(), nullable=True),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('HOMEWORK', 'CLASSWORK', 'QUIZ', 'TEST', 'EXAM', 'PROJECT', 'PARTICIPATION', 'OTHER', name='assessmenttype'), nullable=False),
    sa.Column('scope', sa.Enum('LESSON', 'MODULE', 'COURSE', name='assessmentscope'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_score_columns_course_id'), 'score_columns', ['course_id'], unique=False)
    op.create_index(op.f('ix_score_columns_lesson_id'), 'score_columns', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_score_columns_module_id'), 'score_columns', ['module_id'], unique=False)
    op.create_index(op.f('ix_enrollments_status'), 'enrollments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollments_status'), table_name='enrollments')
    op.drop_index(op.f('ix_score_columns_module_id'), table_name='score_columns')
    op.drop_index(op.f('ix_score_columns_lesson_id'), table_name='score_columns')
    op.drop_index(op.f('ix_score_columns_course_id'), table_name='score_columns')
    op.drop_table('score_columns')
    # ### end Alembic commands ###
