"""sync

Revision ID: 20131969507a
Revises: 
Create Date: 2025-12-26 23:00:49.432293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20131969507a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_tags',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.String(length=36), nullable=True),
    sa.Column('relevance', sa.Integer(), nullable=False, comment='Relevance score (1-10), higher means more relevant'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE')
    )
    op.add_column('order_items', sa.Column('variant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'product_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    op.add_column('reviews', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('reviews', sa.Column('product_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tags', 'parent_id',
               existing_type=sa.VARCHAR(length=36),
               postgresql_using="parent_id::uuid",
               type_=sa.Uuid(),
               comment=None,
               existing_comment='Parent tag for hierarchical structure',
               existing_nullable=True)
    op.create_unique_constraint(None, 'tags', ['id'])
    op.create_foreign_key(None, 'tags', 'tags', ['parent_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_changed_at')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='unique')
    op.alter_column('tags', 'parent_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               comment='Parent tag for hierarchical structure',
               existing_nullable=True)
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_column('reviews', 'product_id')
    op.drop_column('reviews', 'is_deleted')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'variant_id')
    op.drop_table('product_tags')
    # ### end Alembic commands ###
