"""sync

Revision ID: 2c59f088b63b
Revises: 9f652240ea75
Create Date: 2026-01-11 20:26:32.830631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c59f088b63b'
down_revision: Union[str, Sequence[str], None] = '9f652240ea75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('total_modules', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'total_modules')
    # ### end Alembic commands ###
