"""sync

Revision ID: 37e2bf3d3751
Revises: d0e4be22bb8f
Create Date: 2026-01-20 17:13:18.479060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e2bf3d3751'
down_revision: Union[str, Sequence[str], None] = 'd0e4be22bb8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_lessons_created_by'), 'lessons', ['created_by'], unique=False)
    op.create_foreign_key(None, 'lessons', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_created_by'), table_name='lessons')
    op.drop_column('lessons', 'created_by')
    # ### end Alembic commands ###
