"""sync

Revision ID: 4ee6dbc9477e
Revises: 16681b05e717
Create Date: 2026-01-08 13:16:03.508157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ee6dbc9477e'
down_revision: Union[str, Sequence[str], None] = '16681b05e717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

from sqlalchemy.dialects import postgresql

assessment_enum = postgresql.ENUM(
    'ASSIGNMENT', 'ASSESSMENT', 'QUIZ', 'EXAM', 'PROJECT', 
    'HOMEWORK', 'CLASSWORK', 'LAB', 'PRESENTATION', 'OTHER',
    name='assessmenttype',
    create_type=False  # <- prevents automatic creation
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['id'], ['file_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_table('course_images',
    # sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    # sa.Column('course_id', postgresql.UUID(as_uuid=True), nullable=True),
    # sa.Column('is_cover', sa.Boolean(), nullable=False),
    # sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    # sa.ForeignKeyConstraint(['id'], ['file_uploads.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )

    op.create_index(op.f('ix_course_images_course_id'), 'course_images', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_images_is_cover'), 'course_images', ['is_cover'], unique=False)
    op.create_table('user_avatars',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['file_uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sa.Uuid(), nullable=True),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('recorder_id', sa.Uuid(), nullable=False),
    # sa.Column('type', sa.Enum('ASSIGNMENT', 'ASSESSMENT', 'QUIZ', 'EXAM', 'PROJECT', 'HOMEWORK', 'CLASSWORK', 'LAB', 'PRESENTATION', 'OTHER', name='assessmenttype'), nullable=False),
    sa.Column('type', assessment_enum, nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('recorded_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='check_assessment'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'lesson_id', name='uq_enrollment_lesson'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_scores_enrollment_id'), 'scores', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_scores_lesson_id'), 'scores', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_scores_module_id'), 'scores', ['module_id'], unique=False)
    op.create_index(op.f('ix_scores_recorder_id'), 'scores', ['recorder_id'], unique=False)
    op.drop_table('lesson_assessments')
    op.drop_table('lesson_assignments')
    op.drop_table('module_results')
    op.alter_column('certificates', 'course_id',
               existing_type=sa.UUID(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('course_categories', 'course_id',
               existing_type=sa.UUID(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('courses', 'id',
               existing_type=sa.UUID(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('courses_id_key'), 'courses', type_='unique')
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.add_column('enrollments', sa.Column('session', sa.String(length=50), nullable=False))
    op.add_column('enrollments', sa.Column('term', sa.String(length=50), nullable=True))
    op.add_column('enrollments', sa.Column('enrolled_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('enrollments', sa.Column('completed_date', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('uq_student_course'), 'enrollments', type_='unique')
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.drop_constraint(op.f('enrollments_enrolled_by_fkey'), 'enrollments', type_='foreignkey')
    op.drop_column('enrollments', 'enrolled_at')
    op.drop_column('enrollments', 'enrolled_by')
    op.add_column('lessons', sa.Column('course_id', sa.Uuid(), nullable=False))
    op.add_column('lessons', sa.Column('order', sa.Integer(), nullable=False))
    op.add_column('lessons', sa.Column('has_assessment', sa.Boolean(), nullable=False))
    op.add_column('lessons', sa.Column('has_assignment', sa.Boolean(), nullable=False))
    op.alter_column('lessons', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('uq_module_lesson_number'), 'lessons', type_='unique')
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.create_unique_constraint('uq_course_lesson', 'lessons', ['course_id', 'lesson_number'])
    op.create_foreign_key(None, 'lessons', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_column('lessons', 'lesson_date')
    op.create_unique_constraint(None, 'modules', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='unique')
    op.add_column('lessons', sa.Column('lesson_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_constraint('uq_course_lesson', 'lessons', type_='unique')
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.create_unique_constraint(op.f('uq_module_lesson_number'), 'lessons', ['module_id', 'lesson_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('lessons', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('lessons', 'has_assignment')
    op.drop_column('lessons', 'has_assessment')
    op.drop_column('lessons', 'order')
    op.drop_column('lessons', 'course_id')
    op.add_column('enrollments', sa.Column('enrolled_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('enrollments', sa.Column('enrolled_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('enrollments_enrolled_by_fkey'), 'enrollments', 'users', ['enrolled_by'], ['id'])
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.create_unique_constraint(op.f('uq_student_course'), 'enrollments', ['student_id', 'course_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('enrollments', 'completed_date')
    op.drop_column('enrollments', 'enrolled_date')
    op.drop_column('enrollments', 'term')
    op.drop_column('enrollments', 'session')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.create_unique_constraint(op.f('courses_id_key'), 'courses', ['id'], postgresql_nulls_not_distinct=False)
    op.alter_column('courses', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('course_categories', 'course_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('certificates', 'course_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_table('module_results',
    sa.Column('module_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exam_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('module_results_module_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('module_results_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('module_results_pkey')),
    sa.UniqueConstraint('module_id', 'student_id', name=op.f('uq_module_student'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('lesson_assignments',
    sa.Column('lesson_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('lesson_assignments_lesson_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('lesson_assignments_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_assignments_pkey'))
    )
    op.create_table('lesson_assessments',
    sa.Column('lesson_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('lesson_assessments_lesson_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('lesson_assessments_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_assessments_pkey'))
    )
    op.drop_index(op.f('ix_scores_recorder_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_module_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_lesson_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_enrollment_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_table('user_avatars')
    op.drop_index(op.f('ix_course_images_is_cover'), table_name='course_images')
    op.drop_index(op.f('ix_course_images_course_id'), table_name='course_images')
    op.drop_table('course_images')
    # ### end Alembic commands ###
