"""sync

Revision ID: 5890eb8ebda7
Revises: 245e6a63a85f
Create Date: 2026-01-13 14:22:54.406889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5890eb8ebda7'
down_revision: Union[str, Sequence[str], None] = '245e6a63a85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('course_tutors', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'REVOKED', name='coursetutorstatus'), nullable=False))
    # 1️⃣ Create ENUM type explicitly
    coursetutorstatus = sa.Enum(
        'ACTIVE',
        'INACTIVE',
        'REVOKED',
        name='coursetutorstatus'
    )
    coursetutorstatus.create(op.get_bind(), checkfirst=True)

    # 2️⃣ Add column using the enum
    op.add_column(
        'course_tutors',
        sa.Column(
            'status',
            coursetutorstatus,
            nullable=False,
            server_default='ACTIVE'  # IMPORTANT if table already has rows
        )
    )
    # 3️⃣ Remove default (clean schema)
    op.alter_column(
        "course_tutors",
        "status",
        server_default=None
    )
    op.add_column('course_tutors', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.add_column('course_tutors', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('course_tutors', sa.Column('assigned_by', sa.UUID(), nullable=True))
    # op.add_column('course_tutors', sa.Column('id', sa.Uuid(), nullable=False))
    # 1️⃣ Add column as nullable
    op.add_column(
        "course_tutors",
        sa.Column("id", sa.Uuid(), nullable=True),
    )

    # 2️⃣ Backfill existing rows
    op.execute(
        "UPDATE course_tutors SET id = gen_random_uuid() WHERE id IS NULL"
    )

    # 3️⃣ Make column NOT NULL
    op.alter_column(
        "course_tutors",
        "id",
        nullable=False,
    )

    # 4️⃣ (Optional but recommended) Add primary key
    # op.create_primary_key(
    #     "pk_course_tutors",
    #     "course_tutors",
    #     ["id"],
    # )
    op.add_column('course_tutors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('course_tutors', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_course_tutors_course_id'), 'course_tutors', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_tutors_status'), 'course_tutors', ['status'], unique=False)
    op.create_index(op.f('ix_course_tutors_tutor_id'), 'course_tutors', ['tutor_id'], unique=False)
    op.create_index('uq_one_primary_tutor_per_course', 'course_tutors', ['course_id', 'is_primary'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_unique_constraint(None, 'course_tutors', ['id'])
    op.create_foreign_key(None, 'course_tutors', 'users', ['assigned_by'], ['id'])
    op.drop_column('course_tutors', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_tutors', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'course_tutors', type_='foreignkey')
    op.drop_constraint(None, 'course_tutors', type_='unique')
    op.drop_index('uq_one_primary_tutor_per_course', table_name='course_tutors', postgresql_where=sa.text('is_primary = true'))
    op.drop_index(op.f('ix_course_tutors_tutor_id'), table_name='course_tutors')
    op.drop_index(op.f('ix_course_tutors_status'), table_name='course_tutors')
    op.drop_index(op.f('ix_course_tutors_course_id'), table_name='course_tutors')
    op.drop_column('course_tutors', 'updated_at')
    op.drop_column('course_tutors', 'created_at')
    # op.drop_column('course_tutors', 'id')
    op.drop_constraint("pk_course_tutors", "course_tutors", type_="primary")
    op.drop_column("course_tutors", "id")
    op.drop_column('course_tutors', 'assigned_by')
    op.drop_column('course_tutors', 'notes')
    op.drop_column('course_tutors', 'revoked_at')
    op.drop_column('course_tutors', 'status')
    # ### end Alembic commands ###
