"""sync

Revision ID: 5df21c541c3c
Revises: 7e0375f74806
Create Date: 2026-01-10 14:04:33.574974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5df21c541c3c'
down_revision: Union[str, Sequence[str], None] = '7e0375f74806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('enrolled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('enrollments', 'enrolled_date')
    op.add_column('lessons', sa.Column('number', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_course_lesson'), 'lessons', type_='unique')
    op.create_unique_constraint('uq_course_lesson', 'lessons', ['course_id', 'number'])
    op.drop_column('lessons', 'lesson_number')
    op.add_column('parent_students', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('parent_students_student_id_fkey'), 'parent_students', type_='foreignkey')
    op.drop_constraint(op.f('parent_students_parent_id_fkey'), 'parent_students', type_='foreignkey')
    op.create_foreign_key(None, 'parent_students', 'users', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'parent_students', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent_students', type_='foreignkey')
    op.drop_constraint(None, 'parent_students', type_='foreignkey')
    op.create_foreign_key(op.f('parent_students_parent_id_fkey'), 'parent_students', 'parents', ['parent_id'], ['id'])
    op.create_foreign_key(op.f('parent_students_student_id_fkey'), 'parent_students', 'students', ['student_id'], ['id'])
    op.drop_column('parent_students', 'created_at')
    op.add_column('lessons', sa.Column('lesson_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_course_lesson', 'lessons', type_='unique')
    op.create_unique_constraint(op.f('uq_course_lesson'), 'lessons', ['course_id', 'lesson_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('lessons', 'number')
    op.add_column('enrollments', sa.Column('enrolled_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('enrollments', 'enrolled_at')
    # ### end Alembic commands ###
