"""sync

Revision ID: 7e0375f74806
Revises: 4ee6dbc9477e
Create Date: 2026-01-08 14:17:07.308316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e0375f74806'
down_revision: Union[str, Sequence[str], None] = '4ee6dbc9477e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('enrollment_id', sa.Uuid(), nullable=False))
    op.add_column('certificates', sa.Column('issued_by', sa.Uuid(), nullable=False))
    op.add_column('certificates', sa.Column('certificate_number', sa.String(length=50), nullable=False))
    op.add_column('certificates', sa.Column('title', sa.String(length=200), nullable=False))
    op.add_column('certificates', sa.Column('issue_date', sa.Date(), nullable=False))
    op.add_column('certificates', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('certificates', sa.Column('qr_code_url', sa.String(length=500), nullable=True))
    op.add_column('certificates', sa.Column('verification_token', sa.String(length=100), nullable=True))
    op.add_column('certificates', sa.Column('is_revoked', sa.Boolean(), nullable=False))
    op.add_column('certificates', sa.Column('revoked_reason', sa.Text(), nullable=True))
    op.add_column('certificates', sa.Column('final_score', sa.Float(), nullable=True))
    op.add_column('certificates', sa.Column('overall_grade', sa.String(length=5), nullable=True))
    op.add_column('certificates', sa.Column('completion_rate', sa.Float(), nullable=True))
    op.drop_constraint(op.f('uq_certificate'), 'certificates', type_='unique')
    op.create_unique_constraint('uq_certificate', 'certificates', ['student_id', 'enrollment_id'])
    op.create_index(op.f('ix_certificates_certificate_number'), 'certificates', ['certificate_number'], unique=True)
    op.create_index(op.f('ix_certificates_enrollment_id'), 'certificates', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_certificates_issued_by'), 'certificates', ['issued_by'], unique=False)
    op.create_index(op.f('ix_certificates_student_id'), 'certificates', ['student_id'], unique=False)
    op.create_unique_constraint(None, 'certificates', ['verification_token'])
    op.drop_constraint(op.f('certificates_course_id_fkey'), 'certificates', type_='foreignkey')
    op.create_foreign_key(None, 'certificates', 'enrollments', ['enrollment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'certificates', 'users', ['issued_by'], ['id'])
    op.drop_column('certificates', 'course_id')
    op.drop_column('certificates', 'issued_at')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.create_unique_constraint(None, 'courses', ['id'])
    op.add_column('reviews', sa.Column('score_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_reviews_score_id'), 'reviews', ['score_id'], unique=False)
    op.create_foreign_key(None, 'reviews', 'scores', ['score_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'scores', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scores', type_='unique')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_index(op.f('ix_reviews_score_id'), table_name='reviews')
    op.drop_column('reviews', 'score_id')
    op.drop_constraint(None, 'courses', type_='unique')
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.add_column('certificates', sa.Column('issued_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.create_foreign_key(op.f('certificates_course_id_fkey'), 'certificates', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'certificates', type_='unique')
    op.drop_index(op.f('ix_certificates_student_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_issued_by'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_enrollment_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_certificate_number'), table_name='certificates')
    op.drop_constraint('uq_certificate', 'certificates', type_='unique')
    op.create_unique_constraint(op.f('uq_certificate'), 'certificates', ['student_id', 'course_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('certificates', 'completion_rate')
    op.drop_column('certificates', 'overall_grade')
    op.drop_column('certificates', 'final_score')
    op.drop_column('certificates', 'revoked_reason')
    op.drop_column('certificates', 'is_revoked')
    op.drop_column('certificates', 'verification_token')
    op.drop_column('certificates', 'qr_code_url')
    op.drop_column('certificates', 'expiry_date')
    op.drop_column('certificates', 'issue_date')
    op.drop_column('certificates', 'title')
    op.drop_column('certificates', 'certificate_number')
    op.drop_column('certificates', 'issued_by')
    op.drop_column('certificates', 'enrollment_id')
    # ### end Alembic commands ###
