"""sync

Revision ID: 9f652240ea75
Revises: ef977de53673
Create Date: 2026-01-10 18:49:46.848940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f652240ea75'
down_revision: Union[str, Sequence[str], None] = 'ef977de53673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_tutors', 'is_primary',
               existing_type=sa.BOOLEAN(),
               comment='Indicates if this tutor is the primary instructor for the course',
               existing_comment='Indicates if this instructor is the primary instructor for the course',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_tutors', 'is_primary',
               existing_type=sa.BOOLEAN(),
               comment='Indicates if this instructor is the primary instructor for the course',
               existing_comment='Indicates if this tutor is the primary instructor for the course',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
