"""sync

Revision ID: a58f37e14196
Revises: 5b31d0aad862
Create Date: 2026-01-14 17:36:14.960468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a58f37e14196'
down_revision: Union[str, Sequence[str], None] = '5b31d0aad862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_students')
    op.add_column('course_categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('course_categories', 'assigned_at')
    op.add_column('user_roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('user_roles', 'assigned_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('user_roles', 'created_at')
    op.add_column('course_categories', sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('course_categories', 'created_at')
    op.create_table('parent_students',
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=False, comment='User ID of the parent/guardian'),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False, comment='User ID of the student'),
    sa.Column('relationship', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Type of relationship: guardian, biological, adoptive, legal_guardian, etc.'),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Indicates if this is the primary guardian'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Additional notes about the relationship'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name=op.f('parent_students_parent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('parent_students_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'student_id', name=op.f('parent_students_pkey'))
    )
    # ### end Alembic commands ###
