"""sync

Revision ID: aaecb890565d
Revises: f2ad503f2032
Create Date: 2026-01-21 12:13:25.678495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaecb890565d'
down_revision: Union[str, Sequence[str], None] = 'f2ad503f2032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'total_lessons',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('lessons', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('is_published', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('lessons', sa.Column('has_assessment', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('lessons', sa.Column('has_assignment', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_lessons_order'), 'lessons', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_order'), table_name='lessons')
    op.drop_column('lessons', 'has_assignment')
    op.drop_column('lessons', 'has_assessment')
    op.drop_column('lessons', 'is_published')
    op.drop_column('lessons', 'duration_minutes')
    op.alter_column('courses', 'total_lessons',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
