"""sync

Revision ID: aee9b8a0c72e
Revises: 15d12e9d5028
Create Date: 2026-01-20 17:28:01.044047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee9b8a0c72e'
down_revision: Union[str, Sequence[str], None] = '15d12e9d5028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_module_lesson'), 'lessons', type_='unique')
    op.create_unique_constraint('uq_module_lesson', 'lessons', ['module_id', 'order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_module_lesson', 'lessons', type_='unique')
    op.create_unique_constraint(op.f('uq_module_lesson'), 'lessons', ['course_id', 'order'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
