"""sync

Revision ID: b055e81da4bf
Revises: aee9b8a0c72e
Create Date: 2026-01-21 06:19:52.916789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b055e81da4bf'
down_revision: Union[str, Sequence[str], None] = 'aee9b8a0c72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('assessment_max', sa.Float(), nullable=True))
    op.add_column('lessons', sa.Column('assignment_max', sa.Float(), nullable=True))
    op.add_column('lessons', sa.Column('status', sa.String(length=20), nullable=False, server_default="draft",))
    op.alter_column('lessons', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_created_by'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_order'), table_name='lessons')
    op.drop_constraint(op.f('uq_module_lesson'), 'lessons', type_='unique')
    op.drop_constraint(op.f('lessons_course_id_fkey'), 'lessons', type_='foreignkey')
    op.drop_constraint(op.f('lessons_created_by_fkey'), 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'created_by')
    op.drop_column('lessons', 'is_published')
    op.drop_column('lessons', 'has_assessment')
    op.drop_column('lessons', 'has_assignment')
    op.drop_column('lessons', 'duration_minutes')
    op.drop_column('lessons', 'content')
    op.drop_column('lessons', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('has_assignment', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('has_assessment', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('lessons_created_by_fkey'), 'lessons', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('lessons_course_id_fkey'), 'lessons', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_module_lesson'), 'lessons', ['module_id', 'order'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_lessons_order'), 'lessons', ['order'], unique=False)
    op.create_index(op.f('ix_lessons_created_by'), 'lessons', ['created_by'], unique=False)
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.alter_column('lessons', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('lessons', 'status')
    op.drop_column('lessons', 'assignment_max')
    op.drop_column('lessons', 'assessment_max')
    # ### end Alembic commands ###
