"""sync

Revision ID: d2f978cf6530
Revises: ec68fb658c36
Create Date: 2026-01-15 10:08:39.211182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2f978cf6530'
down_revision: Union[str, Sequence[str], None] = 'ec68fb658c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_children', sa.Column('child_id', sa.UUID(), nullable=False, comment='User ID of the child / student'))
    op.alter_column('parent_children', 'relationship_type',
               existing_type=postgresql.ENUM('PARENT', 'GUARDIAN', 'BIOLOGICAL', 'ADOPTIVE', 'LEGAL_GUARDIAN', 'FOSTER', 'OTHER', name='relationshiptype'),
               comment='Type of parent-child relationship',
               existing_comment='Type of parent-student relationship',
               existing_nullable=False)
    op.drop_index(op.f('ix_parent_students_parent_id'), table_name='parent_children')
    op.drop_index(op.f('ix_parent_students_status'), table_name='parent_children')
    op.drop_index(op.f('ix_parent_students_student_id'), table_name='parent_children')
    op.drop_index(op.f('uq_one_primary_parent_per_student'), table_name='parent_children', postgresql_where='(is_primary = true)')
    op.drop_index(op.f('uq_parent_student_pair'), table_name='parent_children')
    op.create_index(op.f('ix_parent_children_child_id'), 'parent_children', ['child_id'], unique=False)
    op.create_index(op.f('ix_parent_children_parent_id'), 'parent_children', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_children_status'), 'parent_children', ['status'], unique=False)
    op.create_index('uq_one_primary_parent_per_child', 'parent_children', ['child_id', 'is_primary'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_index('uq_parent_child_pair', 'parent_children', ['parent_id', 'child_id'], unique=True)
    op.create_unique_constraint(None, 'parent_children', ['id'])
    op.drop_constraint(op.f('parent_students_student_id_fkey'), 'parent_children', type_='foreignkey')
    op.create_foreign_key(None, 'parent_children', 'users', ['child_id'], ['id'], ondelete='CASCADE')
    op.drop_column('parent_children', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_children', sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False, comment='User ID of the student'))
    op.drop_constraint(None, 'parent_children', type_='foreignkey')
    op.create_foreign_key(op.f('parent_students_student_id_fkey'), 'parent_children', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'parent_children', type_='unique')
    op.drop_index('uq_parent_child_pair', table_name='parent_children')
    op.drop_index('uq_one_primary_parent_per_child', table_name='parent_children', postgresql_where=sa.text('is_primary = true'))
    op.drop_index(op.f('ix_parent_children_status'), table_name='parent_children')
    op.drop_index(op.f('ix_parent_children_parent_id'), table_name='parent_children')
    op.drop_index(op.f('ix_parent_children_child_id'), table_name='parent_children')
    op.create_index(op.f('uq_parent_student_pair'), 'parent_children', ['parent_id', 'student_id'], unique=True)
    op.create_index(op.f('uq_one_primary_parent_per_student'), 'parent_children', ['student_id', 'is_primary'], unique=True, postgresql_where='(is_primary = true)')
    op.create_index(op.f('ix_parent_students_student_id'), 'parent_children', ['student_id'], unique=False)
    op.create_index(op.f('ix_parent_students_status'), 'parent_children', ['status'], unique=False)
    op.create_index(op.f('ix_parent_students_parent_id'), 'parent_children', ['parent_id'], unique=False)
    op.alter_column('parent_children', 'relationship_type',
               existing_type=postgresql.ENUM('PARENT', 'GUARDIAN', 'BIOLOGICAL', 'ADOPTIVE', 'LEGAL_GUARDIAN', 'FOSTER', 'OTHER', name='relationshiptype'),
               comment='Type of parent-student relationship',
               existing_comment='Type of parent-child relationship',
               existing_nullable=False)
    op.drop_column('parent_children', 'child_id')
    # ### end Alembic commands ###
