"""sync

Revision ID: e95556d5bfb1
Revises: 16fa66b1e79b
Create Date: 2026-01-23 13:39:00.638184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95556d5bfb1'
down_revision: Union[str, Sequence[str], None] = '16fa66b1e79b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('type', sa.Enum('HOMEWORK', 'CLASSWORK', 'QUIZ', 'TEST', 'EXAM', 'PROJECT', 'PARTICIPATION', 'OTHER', name='assessmenttype'), nullable=False))
    op.create_unique_constraint(None, 'score_columns', ['id'])
    op.add_column('scores', sa.Column('column_id', sa.Uuid(), nullable=True))
    op.add_column('scores', sa.Column('type', sa.Enum('HOMEWORK', 'CLASSWORK', 'QUIZ', 'TEST', 'EXAM', 'PROJECT', 'PARTICIPATION', 'OTHER', name='assessmenttype'), nullable=False))
    op.create_index(op.f('ix_scores_column_id'), 'scores', ['column_id'], unique=False)
    op.create_foreign_key(None, 'scores', 'score_columns', ['column_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_index(op.f('ix_scores_column_id'), table_name='scores')
    op.drop_column('scores', 'type')
    op.drop_column('scores', 'column_id')
    op.drop_constraint(None, 'score_columns', type_='unique')
    op.drop_column('assessments', 'type')
    # ### end Alembic commands ###
