"""sync

Revision ID: ec68fb658c36
Revises: a58f37e14196
Create Date: 2026-01-14 17:53:22.728798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec68fb658c36'
down_revision: Union[str, Sequence[str], None] = 'a58f37e14196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_students',
    sa.Column('parent_id', sa.UUID(), nullable=False, comment='User ID of the parent/guardian'),
    sa.Column('student_id', sa.UUID(), nullable=False, comment='User ID of the student'),
    sa.Column('relationship_type', sa.Enum('PARENT', 'GUARDIAN', 'BIOLOGICAL', 'ADOPTIVE', 'LEGAL_GUARDIAN', 'FOSTER', 'OTHER', name='relationshiptype'), nullable=False, comment='Type of parent-student relationship'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='linkstatus'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Indicates if this is the primary guardian'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('linked_by', sa.UUID(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_parent_students_parent_id'), 'parent_students', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_students_status'), 'parent_students', ['status'], unique=False)
    op.create_index(op.f('ix_parent_students_student_id'), 'parent_students', ['student_id'], unique=False)
    op.create_index('uq_one_primary_parent_per_student', 'parent_students', ['student_id', 'is_primary'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_index('uq_parent_student_pair', 'parent_students', ['parent_id', 'student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_parent_student_pair', table_name='parent_students')
    op.drop_index('uq_one_primary_parent_per_student', table_name='parent_students', postgresql_where=sa.text('is_primary = true'))
    op.drop_index(op.f('ix_parent_students_student_id'), table_name='parent_students')
    op.drop_index(op.f('ix_parent_students_status'), table_name='parent_students')
    op.drop_index(op.f('ix_parent_students_parent_id'), table_name='parent_students')
    op.drop_table('parent_students')
    # ### end Alembic commands ###
