"""sync

Revision ID: ef977de53673
Revises: b53196d2d6c5
Create Date: 2026-01-10 17:53:22.845790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef977de53673'
down_revision: Union[str, Sequence[str], None] = 'b53196d2d6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parents')
    # op.drop_table('students')
    op.add_column('course_categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('course_categories_category_id_fkey'), 'course_categories', type_='foreignkey')
    op.drop_constraint(op.f('course_categories_course_id_fkey'), 'course_categories', type_='foreignkey')
    op.create_foreign_key(None, 'course_categories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'course_categories', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.add_column('course_tutors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('course_tutors', sa.Column('is_primary', sa.Boolean(), nullable=False, server_default=sa.text('false'), comment='Indicates if this instructor is the primary instructor for the course'))
    op.add_column('parent_students', sa.Column('notes', sa.String(length=500), nullable=True, comment='Additional notes about the relationship'))
    op.alter_column('parent_students', 'parent_id',
               existing_type=sa.UUID(),
               comment='User ID of the parent/guardian',
               existing_nullable=False)
    op.alter_column('parent_students', 'student_id',
               existing_type=sa.UUID(),
               comment='User ID of the student',
               existing_nullable=False)
    op.alter_column('parent_students', 'relationship',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='Type of relationship: guardian, biological, adoptive, legal_guardian, etc.')
    op.alter_column('parent_students', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='Indicates if this is the primary guardian')
    op.alter_column('parent_students', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('role_permissions', sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # op.drop_constraint(op.f('submissions_student_id_fkey'), 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'names',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'names',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('user_roles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_student_id_fkey'), 'submissions', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_column('role_permissions', 'granted_at')
    op.alter_column('parent_students', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('parent_students', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='Indicates if this is the primary guardian')
    op.alter_column('parent_students', 'relationship',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='Type of relationship: guardian, biological, adoptive, legal_guardian, etc.')
    op.alter_column('parent_students', 'student_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User ID of the student',
               existing_nullable=False)
    op.alter_column('parent_students', 'parent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User ID of the parent/guardian',
               existing_nullable=False)
    op.drop_column('parent_students', 'notes')
    op.drop_column('course_tutors', 'is_primary')
    op.drop_column('course_tutors', 'created_at')
    op.drop_constraint(None, 'course_categories', type_='foreignkey')
    op.drop_constraint(None, 'course_categories', type_='foreignkey')
    op.create_foreign_key(op.f('course_categories_course_id_fkey'), 'course_categories', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(op.f('course_categories_category_id_fkey'), 'course_categories', 'categories', ['category_id'], ['id'])
    op.drop_column('course_categories', 'created_at')
    op.create_table('students',
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('students_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('students_pkey')),
    sa.UniqueConstraint('id', name=op.f('students_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name=op.f('students_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('parents',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('relationship_to_student', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('emergency_contact', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('parents_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('parents_pkey')),
    sa.UniqueConstraint('id', name=op.f('parents_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name=op.f('parents_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
