"""sync

Revision ID: f2ad503f2032
Revises: b055e81da4bf
Create Date: 2026-01-21 11:49:02.726869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ad503f2032'
down_revision: Union[str, Sequence[str], None] = 'b055e81da4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'total_modules',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('lessons', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_lessons_created_by'), 'lessons', ['created_by'], unique=False)
    op.create_index(op.f('ix_lessons_module_id'), 'lessons', ['module_id'], unique=False)
    op.create_unique_constraint('uq_module_lesson_order', 'lessons', ['module_id', 'order'])
    op.create_foreign_key(None, 'lessons', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_constraint('uq_module_lesson_order', 'lessons', type_='unique')
    op.drop_index(op.f('ix_lessons_module_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_created_by'), table_name='lessons')
    op.drop_column('lessons', 'created_by')
    op.alter_column('courses', 'total_modules',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
