"""sync

Revision ID: f4e42b381090
Revises: 7f27caf02104
Create Date: 2026-01-25 07:07:52.119466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e42b381090'
down_revision: Union[str, Sequence[str], None] = '7f27caf02104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('COMPLETED', 'ONGOING', 'UPCOMING', 'CANCELLED', name='lesson_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'status',
               existing_type=sa.Enum('COMPLETED', 'ONGOING', 'UPCOMING', 'CANCELLED', name='lesson_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    # ### end Alembic commands ###
